import { chromium } from 'playwright';
const B='https://emerald-spa-wellness.vercel.app';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1440,height:900}});
const p=await ctx.newPage();
await p.goto(B+'/',{waitUntil:'networkidle'}); await p.waitForTimeout(4000);
await p.screenshot({path:'audit/shots/LIVE-home.png'});
await p.evaluate(()=>window.scrollTo(0,900)); await p.waitForTimeout(1800);
await p.screenshot({path:'audit/shots/LIVE-home-scroll.png'});
await p.goto(B+'/about',{waitUntil:'networkidle'}); await p.waitForTimeout(2500);
await p.evaluate(()=>window.scrollTo(0,2100)); await p.waitForTimeout(1600);
await p.screenshot({path:'audit/shots/LIVE-team.png'});
await p.goto(B+'/brand',{waitUntil:'networkidle'}); await p.waitForTimeout(2500);
await p.evaluate(()=>window.scrollTo(0,1200)); await p.waitForTimeout(1500);
await p.screenshot({path:'audit/shots/LIVE-brand.png'});
const m=await (await b.newContext({viewport:{width:375,height:812}})).newPage();
await m.goto(B+'/services',{waitUntil:'networkidle'}); await m.waitForTimeout(2500);
await m.screenshot({path:'audit/shots/LIVE-services-mobile.png'});
await b.close(); console.log('captured');
